import { normalizePrintDisplayMode } from "@shared/document-engine/display-mode";

export interface BuildPrintPayloadArgs {
  docForm: Record<string, any>;
  items: Record<string, any>[];
  customer?: Record<string, any> | null;
  documentId?: number;
  formTemplateId?: number | null;
  projectId?: number | null;
  displayMode?: string;
}

export function buildPrintPayload({
  docForm,
  items,
  customer,
  documentId,
  formTemplateId,
  projectId,
  displayMode,
}: BuildPrintPayloadArgs) {
  return {
    document: {
      id: documentId || 0,
      type: docForm.type,
      documentNumber: docForm.documentNumber,
      date: docForm.date,
      validUntil: docForm.validUntil,
      subject: docForm.subject,
      headerText: docForm.headerText,
      footerText: docForm.footerText,
      beforeWorkText: docForm.beforeWorkText,
      beforeTotalsText: docForm.beforeTotalsText,
      afterTotalsText: docForm.afterTotalsText,
      taxRate: docForm.taxRate,
      paymentTermDays: docForm.paymentTermDays,
      skontoDays: docForm.skontoDays,
      skontoPercent: docForm.skontoPercent,
      skontoNurMaterial: docForm.skontoNurMaterial === true,
      status: "entwurf",
      customTypeLabel: docForm.customTypeLabel || null,
      retentionPercent: docForm.retentionPercent || "0",
      parentDocumentId: docForm.parentDocumentId || null,
      abschlagNumber: docForm.abschlagNumber || null,
      netTotal: docForm.netTotal || "0",
      taxAmount: docForm.taxAmount || "0",
      grossTotal: docForm.grossTotal || "0",
      laborTotal: docForm.laborTotal || "0",
      previouslyInvoiced: docForm.previouslyInvoiced || "0",
      dezimalstellenMengen: docForm.dezimalstellenMengen ?? 2,
      dezimalstellenPreise: docForm.dezimalstellenPreise ?? 2,
      hideNetto: docForm.hideNetto ?? false,
      hideMwst: docForm.hideMwst ?? false,
      hideGesamt: docForm.hideGesamt ?? false,
      showLohnanteil: docForm.showLohnanteil ?? false,
      abschlagVerrechnungen: docForm.abschlagVerrechnungen || [],
      skontoImDokument: docForm.skontoImDokument !== false,
      par13b: docForm.par13b || false,
      internpositionenVerbergen: docForm.internpositionenVerbergen !== false,
      autoPositionNumbers: docForm.autoPositionNumbers !== false,
      positionNumberStep: docForm.positionNumberStep ?? 1,
      positionNumberStart: docForm.positionNumberStart ?? 1,
    },
    items: items.map((it, idx) => ({
      id: it.id || idx + 1,
      type: it.type || "position",
      positionNumber: it.positionNumber || "",
      title: it.title || null,
      description: it.description || null,
      articleNumber: it.articleNumber || null,
      quantity: it.quantity || "0",
      unit: it.unit || "",
      unitPrice: it.unitPrice || "0",
      totalPrice: it.totalPrice || "0",
      sortOrder: it.sortOrder ?? idx,
      parentItemId: it.parentItemId || null,
      _clientId: it._clientId || null,
      _parentClientId: it._parentClientId || null,
      pageBreakBefore: it.pageBreakBefore || false,
      positionFlag: it.positionFlag || null,
      flagLabel: it.flagLabel || null,
      materialPrice: it.materialPrice || null,
      materialCost: it.materialCost || null,
      laborCost: it.laborCost || null,
      equipmentCost: it.equipmentCost || null,
      externalCost: it.externalCost || null,
      materialMarkup: it.materialMarkup || null,
      laborMarkup: it.laborMarkup || null,
      equipmentMarkup: it.equipmentMarkup || null,
      externalMarkup: it.externalMarkup || null,
      laborPrice: it.laborPrice || null,
      priceFollowsCost: it.priceFollowsCost || false,
      originalQuantity: it.originalQuantity || null,
      afterTotals: it.afterTotals || false,
      laborTime: it.laborTime || null,
      fontBold: it.fontBold || false,
      fontItalic: it.fontItalic || false,
      fontUnderline: it.fontUnderline || false,
      fontSize: it.fontSize || null,
      fontColor: it.fontColor || null,
      discountPercent: it.discountPercent || null,
      discountBase: it.discountBase || null,
    })),
    customerId: customer?.id || null,
    formTemplateId: formTemplateId || null,
    projectId: projectId || null,
    displayMode: normalizePrintDisplayMode(displayMode),
  };
}
